### ISSUE TITLE
NBT Void randomly crasges when opening up the item tab

### ISSUE THREAD

**Issue by RexkyGG** [White-145/nbtvoid#1]

**Comment by White-145** [comment]
can i see the logs?

**Comment by RexkyGG** [comment]
> can i see the logs?

yeah, i will send them if it happens again

**Comment by RexkyGG** [comment]
---- Minecraft Crash Report ----
// My bad.

Time: 2023-07-08 13:15:18
Description: mouseDragged event handler

java.lang.NullPointerException: The validated object is null
	at java.base/java.util.Objects.requireNonNull(Objects.java:334)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:224)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:206)
	at net.minecraft.class_2371.set(class_2371.java:52)
	at net.minecraft.class_1277.method_5447(class_1277.java:140)
	at net.minecraft.class_481$class_483.method_2473(class_481.java:129)
	at net.minecraft.class_481.method_25403(class_481.java:712)
	at net.minecraft.class_312.method_1602(class_312.java:201)
	at net.minecraft.class_437.method_25412(class_437.java:409)
	at net.minecraft.class_312.method_1600(class_312.java:201)
	at net.minecraft.class_312.method_22689(class_312.java:168)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22688(class_312.java:168)
	at org.lwjgl.glfw.GLFWCursorPosCallbackI.callback(GLFWCursorPosCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:212)
	at net.minecraft.class_1041.method_15998(class_1041.java:288)
	at net.minecraft.class_310.method_1523(class_310.java:1241)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.Objects.requireNonNull(Objects.java:334)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:224)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:206)
	at net.minecraft.class_2371.set(class_2371.java:52)
	at net.minecraft.class_1277.method_5447(class_1277.java:140)
	at net.minecraft.class_481$class_483.method_2473(class_481.java:129)
	at net.minecraft.class_481.method_25403(class_481.java:712)
	at net.minecraft.class_312.method_1602(class_312.java:201)
	at net.minecraft.class_437.method_25412(class_437.java:409)
	at net.minecraft.class_312.method_1600(class_312.java:201)
	at net.minecraft.class_312.method_22689(class_312.java:168)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22688(class_312.java:168)
	at org.lwjgl.glfw.GLFWCursorPosCallbackI.callback(GLFWCursorPosCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:212)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_481
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:409)
	at net.minecraft.class_312.method_1600(class_312.java:201)
	at net.minecraft.class_312.method_22689(class_312.java:168)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22688(class_312.java:168)
	at org.lwjgl.glfw.GLFWCursorPosCallbackI.callback(GLFWCursorPosCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:212)
	at net.minecraft.class_1041.method_15998(class_1041.java:288)
	at net.minecraft.class_310.method_1523(class_310.java:1241)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 4 total; [class_746['Isaaceeeeee'/173495, l='ClientLevel', x=-200.79, y=88.76, z=-126.80], class_745['god'/173573, l='ClientLevel', x=-199.74, y=87.73, z=-127.63], class_745['0opsyt'/552, l='ClientLevel', x=-196.48, y=90.12, z=-125.05], class_745['RedstoneKing2'/3, l='ClientLevel', x=-204.77, y=86.75, z=-127.53]]
	Chunk stats: 256, 121
	Level dimension: minecraft:overworld
	Level spawn location: World: (192,64,-128), Section: (at 0,0,0 in 12,4,-8; chunk contains blocks 192,0,-128 to 207,255,-113), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 184707 game time, 1528707 day time
	Server brand: Paper (Velocity)
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:821)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
